# Generated by Django 4.2.4 on 2023-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_remove_cartitem_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
