# Generated by Django 4.2.4 on 2023-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_alter_profile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile"),
        ),
    ]
