# Generated by Django 4.2.4 on 2023-08-25 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0012_remove_offer_end_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
    ]
