# Generated by Django 4.2.4 on 2023-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0013_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount_price",
            field=models.BigIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="minimum_amount",
            field=models.BigIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name="offer",
            name="percentage",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="quantity",
            field=models.BigIntegerField(default=0),
        ),
    ]
