# Generated by Django 4.2.4 on 2023-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_address_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="alternate_number",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="address",
            name="pincode",
            field=models.BigIntegerField(),
        ),
    ]
