# Generated by Django 4.2.4 on 2023-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_order_user_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="coupon_price",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.BigIntegerField(),
        ),
    ]
